#!/usr/bin/env bash

BASE_DIR="$(cd "$(dirname "$0")"; pwd)" || exit 2

IFS=$'\n'
entrylist=('Go Back')
rawentry="$(find $BASE_DIR/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

COLUMNS=12


#This function is to display the top header in a centred alignment!
display_center(){
    columns="$(tput cols)"
    while IFS= read -r line; do
        printf "%*s\n" $(( (${#line} + columns) / 2)) "$line"
    done < "$1"
}

# Function to center multiline text horizontally and vertically in the terminal
center_multiline_text() {
    local text="$1"
    # Convert input into an array where each line is an element
    IFS=$'\n' read -r -d '' -a lines <<< "$text"

    # Get terminal width and height
    local term_width=$(tput cols)
    local term_height=$(tput lines)

    # Calculate vertical padding
    local total_lines=${#lines[@]}
    local vertical_padding=$(( (term_height - total_lines) / 2 ))

    # Clear the screen
    clear

    # Print vertical padding
    for (( i=0; i<vertical_padding; i++ )); do
        echo ""
    done

    # Center each line of the ASCII art
    for line in "${lines[@]}"; do
        local line_length=${#line}
        local horizontal_padding=$(( (term_width - line_length) / 2 ))
        printf "%${horizontal_padding}s%s\n" "" "$line"
    done
}

#This string is to be displayed as a custom "title header" at the top, feel free to customise it, as most Terminals in Fallout have their own custom one based on their owner!
greeter=$'
            Proto Personal Text Based Log Manufactured and Maintained by The Archive In Between
_____________________________________________________________________________________________________________'



#Main Menu Screen
mainmenufunc () {
    clear

    # Display the Menu text
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa

    # Display the menu options
    COLUMNS=12
    options=("Mission Control" "View Overseer Logs" "Portal Gate Status" "Broadcasts" "Geiger Counter" "Exit Terminal")
    selected=0

    # Function to print the menu options with cursor highlighting
    print_menu() {
        for i in "${!options[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m${options[$i]}\e[0m"
            else
                echo "${options[$i]}"
            fi
        done
    }

    # Print the initial menu
    print_menu

    # Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#options[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#options[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                case $selected in
                    0)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        mission_mainfunc
                        ;;
                    1)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        logfunc
                        ;;
                    2)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        portalstatfunc
                        ;;
                    3)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        broadcastfunc
                        ;;
                    4)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        geiger_counter
                        ;;
                    5)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        echo Goodbye! && exit
                        ;;
                esac
                break
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}


# Function to display the main menu
mission_mainfunc() {
    clear

    # Display the Menu text
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa

    # Display the menu options
    COLUMNS=12
    options=("View Missions" "Accepted Missions" "Completed Missions" "Return to Main Menu")
    selected=0

    # Function to print the menu options with cursor highlighting
    print_menu() {
        for i in "${!options[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m$i) ${options[$i]}\e[0m"
            else
                echo "$i) ${options[$i]}"
            fi
        done
    }

    # Print the initial menu
    print_menu

    # Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#options[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#options[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                case $selected in
                    0)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        view_missions
                        ;;
                    1)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        accept_mission
                        ;;
                    2)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        complete_mission
                        ;;
                    3)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        mainmenufunc
                        ;;
                esac
                break
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}

# Function to display the list of missions
view_missions() {
    clear

    # Display the Menu text
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    display_center "$BASE_DIR/greeterheader.txt" | pv -qL 400
    echo "$greeter" | pv -qL 400
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo Available Missions: | pv -qL 200
    echo ----------------------- | pv -qL 200

    # Read the available missions from a txt file
    mission_file="$BASE_DIR/missions.txt"
    if [ -f "$mission_file" ]; then
        IFS=$'\n' read -d '' -r -a missions < "$mission_file"
        for ((i=0; i<${#missions[@]}; i++)); do
            echo "$(($i+1))) ${missions[$i]}"
        done

        read -p "Enter the mission number to accept: " mission_num
        case $mission_num in
            [1-9]|[1-9][0-9])
                mission="${missions[$mission_num-1]}"
                echo "Mission '$mission'" >> "$BASE_DIR/accepted_missions.txt"
                # Remove the accepted mission from the missions file
                sed -i "${mission_num}d" "$mission_file"
                ;;
            *)
                echo "Invalid mission number."
                ;;
        esac
    else
        echo "No missions available."
    fi

    read -p "Press any key to return to the main menu..." any_key
    mission_mainfunc
}


# Function to accept a mission

accept_mission() {
    clear

    # Display the Menu text
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    display_center "$BASE_DIR/greeterheader.txt" | pv -qL 400
    echo "$greeter" | pv -qL 400
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo Accepted Missions: | pv -qL 200
    echo ----------------------- | pv -qL 200

    # Read the accepted missions from the file
    accepted_missions_file="$BASE_DIR/accepted_missions.txt"
    if [ -f "$accepted_missions_file" ]; then
        IFS=$'\n' read -d '' -r -a accepted_missions < "$accepted_missions_file"
        for ((i=0; i<${#accepted_missions[@]}; i++)); do
            echo "$(($i+1))) ${accepted_missions[$i]}"
        done

        # Prompt the user to choose an action
        read -p "Enter the mission number to complete or 'b' to go back: " mission_num
        case $mission_num in
            [1-9]|[1-9][0-9])
                # Subtract 1 from the mission number to get the index
                local index=$((mission_num - 1))

                # Check if the index is within the range of accepted missions
                if [ $index -ge 0 ] && [ $index -lt ${#accepted_missions[@]} ]; then
                    local selected_mission="${accepted_missions[$index]}"
                    echo "Completing mission: $selected_mission"
                    # Add code here to complete the selected mission

                    # Remove the completed mission from the accepted missions file
                    sed -i "${index}d" "$accepted_missions_file"

                    # Add the completed mission to the completed missions file
                    completed_missions_file="$BASE_DIR/completed_missions.txt"
                    echo "$selected_mission" >> "$completed_missions_file"
                else
                    echo "Invalid mission number."
                fi
                ;;
            b)
                mission_mainfunc
                ;;
            *)
                echo "Invalid input."
                ;;
        esac
    else
        echo "No accepted missions."
    fi

    read -p "Press any key to return to the main menu..." any_key
    mission_mainfunc
}


# Function to complete a mission
complete_mission() {
clear

# Display the Menu text
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
display_center "$BASE_DIR/greeterheader.txt" | pv -qL 400
echo "$greeter" | pv -qL 400
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Completed Missions: | pv -qL 200
echo ----------------------- | pv -qL 200

# Read the completed missions from the file
completed_missions_file="$BASE_DIR/completed_missions.txt"
if [ -f "$completed_missions_file" ]; then
    IFS=$'\n' read -d '' -r -a completed_missions < "$completed_missions_file"
    for ((i=0; i<${#completed_missions[@]}; i++)); do
        echo "$(($i+1))) ${completed_missions[$i]}"
    done
else
    echo "No completed missions."
fi

read -p "Press any key to return to the main menu..." any_key
mission_mainfunc
}

logfunc() {
    clear

    # Display the Menu text
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa

    # Display the menu options
    COLUMNS=12
    options=("View Journal Entries" "Log a Journal Entry" "Delete a Journal Entry" "Exit Log")
    selected=0

    # Function to print the menu options with cursor highlighting
    print_menu() {
        for i in "${!options[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m${options[$i]}\e[0m"
            else
                echo "${options[$i]}"
            fi
        done
    }

    # Print the initial menu
    print_menu

# Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#options[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#options[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                case $selected in
                    0)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        viewentriesfunc
                        ;;
                    1)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        writeentryfunc
                        ;;
                    2)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        deleteentryfunc
                        ;;
                    3)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        mainmenufunc
                        ;;
                esac
                break
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}

portalstatfunc () {
    clear

    # Display the Menu text
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa

    # Display the menu options
    COLUMNS=12
    options=("Sector Status" "Fault Logs" "Exit Status")
    selected=0

     # Function to print the menu options with cursor highlighting
    print_menu() {
        for i in "${!options[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m${options[$i]}\e[0m"
            else
                echo "${options[$i]}"
            fi
        done
    }

    # Print the initial menu
    print_menu

# Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#options[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#options[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                case $selected in
                    0)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        show_portal_status
                        ;;
                    1)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        fault_logfunc
                        ;;
                    2)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        mainmenufunc
                        ;;
                esac
                break
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}


show_portal_status() {
    # Directory where the portal status file will be saved
    local status_dir="portal_status"
    local status_file="${status_dir}/status.txt"

    # Check if the directory exists, if not create it
    if [ ! -d "$status_dir" ]; then
        mkdir -p "$status_dir"
    fi

    # Check if the status file already exists
    if [ -f "$status_file" ]; then
        # Display the existing status file
        cat "$status_file"
    else
        # Declare an array of sectors
        local sectors=("Sector A" "Sector B" "Sector C" "Sector D" "Sector E" "Sector F")

        # Declare an array of possible statuses
        local statuses=("Functioning" "Shutdown" "Under Maintenance")

        clear

        # Output header to both terminal and file
        echo "Portal Status of Sectors in Sigil:"
        echo "----------------------------------" | tee "$status_file"

        # Loop through each sector to assign a random status
        for sector in "${sectors[@]}"; do
            # Generate a random index to select a random status
            local random_status_index=$((RANDOM % ${#statuses[@]}))
            local random_status=${statuses[$random_status_index]}

            # Display the sector and its randomly selected status and append to file
            printf "%-10s: %s\n" "$sector" "$random_status" | tee -a "$status_file"
        done

        # Output footer to both terminal and file
        echo "----------------------------------" | tee -a "$status_file"
        echo "Status information is updated frequently. Please check back for real-time updates." | tee -a "$status_file"
    fi

    # Wait for user input before returning to the main menu
    read -p "Press Enter to return to the main menu..."

    portalstatfunc
}


fault_logfunc () 
{
    # Adding all the text files as individual strings to be used as a selection menu
    entrylist=('Go Back')
    rawentry="$(find $BASE_DIR/fault_logs -type f)"
    for i in $rawentry; do
        i=${i##*/}
        entrylist+=("$i")
    done

    # Display the Menu text
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    
    # Display the menu options
    COLUMNS=12
    selected=0

    # Function to print the menu options with cursor highlighting
    print_menu() {
        for i in "${!entrylist[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m${entrylist[$i]}\e[0m"
            else
                echo "${entrylist[$i]}"
            fi
        done
    }

    # Print the initial menu
    print_menu

    # Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#entrylist[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#entrylist[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                case ${entrylist[selected]} in
                    "Go Back")
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        portalstatfunc
                        ;;
                    *)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        ;;
                esac

                # Display the selected entry
                clear
                display_center "$BASE_DIR/greeterheader.txt"
                echo "$greeter"
                echo
                play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
                echo "${entrylist[selected]}:"  | pv -qL 200
                play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
                cat< "$BASE_DIR/fault_logs/${entrylist[selected]}"  | pv -qL 200
                echo
                read -p "Press enter to continue"
                play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa

                # Go back to main menu
                portalstatfunc
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}


#############################################################################
broadcastfunc () 
{
   clear

    # Display the Menu text
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa

    # Display the menu options
    COLUMNS=12
    options=("View Broadcasts" "Exit")
    selected=0

     # Function to print the menu options with cursor highlighting
    print_menu() {
        for i in "${!options[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m${options[$i]}\e[0m"
            else
                echo "${options[$i]}"
            fi
        done
    }

    # Print the initial menu
    print_menu

# Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#options[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#options[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                case $selected in
                    0)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        viewbroadcasts
                        ;;
                    1)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        mainmenufunc
                        ;;

                esac
                break
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}

viewbroadcasts() {
    # Adding all the .wav files as individual strings to be used as a selection menu
    entrylist=('Go Back')
    rawentry="$(find $BASE_DIR/broadcasts -type f -name "*.wav")"
    for i in $rawentry; do
        i=${i##*/}
        entrylist+=("$i")
    done

    # Display the Menu text
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo "Which Entry would you like to access?" | pv -qL 200
    
    # Display the menu options
    COLUMNS=12
    selected=0
    print_menu() {
        for i in "${!entrylist[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m${entrylist[$i]}\e[0m"
            else
                echo "${entrylist[$i]}"
            fi
        done
    }

    print_menu

    # Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#entrylist[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#entrylist[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                case ${entrylist[$selected]} in
                    "Go Back")
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        mainmenufunc
                        ;;
                    *)
                        # Plays the selected .wav file
                        echo "Now Playing: ${entrylist[$selected]}" | pv -qL 200
                        play -q "$BASE_DIR/broadcasts/${entrylist[$selected]}" -t alsa
                        ;;
                esac

                # Displaying information about the selected entry
                clear
                display_center "$BASE_DIR/greeterheader.txt"
                echo "$greeter"
                echo "Just Played: ${entrylist[$selected]}" | pv -qL 200
                echo
                play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa

                echo
                read -p "Press enter to continue"
                play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                
                # Goes back to main menu
                viewbroadcasts
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}


############################################################
#Option 1 Menu, Viewing Journal Entries
viewentriesfunc () {
    # Adding all the text files as individual strings to be used as a selection menu
    entrylist=('Go Back')
    rawentry="$(find $BASE_DIR/entries -type f)"
    for i in $rawentry; do
        i=${i##*/}
        entrylist+=("$i")
    done

    # Display the Menu text
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo "Which Entry would you like to access?" | pv -qL 200
    
    # Display the menu options
    COLUMNS=12
    selected=0
    print_menu() {
        for i in "${!entrylist[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m${entrylist[$i]}\e[0m"
            else
                echo "${entrylist[$i]}"
            fi
        done
    }

    print_menu

    # Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#entrylist[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#entrylist[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                if [[ $selected -eq 0 ]]; then
                    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                    mainmenufunc
                else
                    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                    clear
                    display_center "$BASE_DIR/greeterheader.txt"
                    echo "$greeter"
                    echo
                    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
                    echo "${entrylist[$selected]}:"  | pv -qL 200
                    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
                    cat "$BASE_DIR/entries/${entrylist[$selected]}"  | pv -qL 200
                    echo
                    read -p "Press enter to continue"
                    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                    mainmenufunc
                fi
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}

#menu for writing an entry
writeentryfunc () 
{

#displays menu text
clear
display_center "$BASE_DIR/greeterheader.txt"
echo "$greeter" 
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "Name the entry?" | pv -qL 200

#reads user input
read entrynameinput 
play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa

#displays menu text again
clear
display_center "$BASE_DIR/greeterheader.txt"
echo "$greeter" 
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Press CTRL+D to finalise entry  | pv -qL 200
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo $entrynameinput:  | pv -qL 200
echo
#uses cat text editor to write entries. ctrl+d to finish
cat >"$BASE_DIR/entries/$entrynameinput"
cat "$BASE_DIR/entries/$entrynameinput"
clear
play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa

#returns to mainmenu
mainmenufunc


}

#menu to delete an entry
deleteentryfunc () 
{

#adding all the text files as individual strings to be used as a selection menu
entrylist=('Go Back')
rawentry="$(find $BASE_DIR/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

    #displays menu text
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo Which Entry would you like to delete? | pv -qL 200
    
    #displays menu options
    COLUMNS=12
    select readoption in ${entrylist[@]}
    do
    case $readoption in
    "Go Back")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    mainmenufunc
    ;;
        *)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    ;;
    esac
    
    #displays menu text again
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    echo
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo "Delete $readoption? Type Operator Passcode to Continue"  | pv -qL 200
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    
    #detects user input if they typed in "yes". case insensitive as it converts it to all caps
    read confirmdeletion
        if  [[ ${confirmdeletion} == "Yes" ]]
        then
        rm -f "$BASE_DIR/entries/$readoption"
        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
        echo FILE DELETED!
        play -q  $BASE_DIR/ui_hacking_passgood.wav -t alsa
        sleep 0.1
        mainmenufunc
        
        #if something other than yes was typed in
        else
        echo OPERATION CANCELLED
        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
        play -q  $BASE_DIR/ui_hacking_passbad.wav -t alsa
        sleep 0.2
        
        
        #goes back to main menu
        mainmenufunc
        fi
        done
}

# Function to check for a connected security key and grant access
check_security_key() {
    # Define the vendor and product ID of your security key
    local vendor_id="0483"  # Replace XXXX with your key's vendor ID
    local product_id="5741"  # Replace YYYY with your key's product ID

    # Use lsusb to check if the device is connected
    if lsusb | grep -q "ID $vendor_id:$product_id"; then
        clear
        bypass_good_art=$(cat <<-EOF
    Terminal Bypass Key is Connected.
    Please stand by.
EOF
)

        center_multiline_text "$bypass_good_art."
        sleep 1.5
        terminal_func
    else
        clear
        bypass_bad_art=$(cat <<-EOF
    Terminal Bypass key is Not Connected.
    Access Denied.
    Returning to main menu
EOF
)

        center_multiline_text "$bypass_bad_art."
        sleep 1.5
        startupfunc
    fi
}

# Function to ask for login password
terminal_func () {
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    echo
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo "Enter command" | pv -qL 200
    read command
    if [[ "$command" == "sysadmin571_bypass/:" ]]; then
        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
        play -q $BASE_DIR/ui_hacking_passgood.wav -t alsa
        sleep 0.5
        echo "Launching Terminal Bypass"
        sleep 1.5
        hacking_game
    elif [[ "$command" == "exit" ]]; then
        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
        clear
        echo "Goodbye!" && startupfunc
        sleep 1.5 
        startupfunc
    else
        play -q $BASE_DIR/ui_hacking_passbad.wav -t alsa
        echo "Unknown Command. Please try again." | pv -qL 200
        clear
        terminal_func
    fi
}


# Function to ask for login password
loginfunc () {
clear
display_center "$BASE_DIR/greeterheader.txt"
echo "$greeter"
echo
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "Enter login password:" | pv -qL 200
read password
if [[ "$password" == "pterodactyl" ]]; then
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    play -q $BASE_DIR/ui_hacking_passgood.wav -t alsa
    sleep 0.5
    welcome_art=$(cat <<-EOF
    Access Granted.
    Welcome, Overseer.
EOF
)

    center_multiline_text "$welcome_art."
    sleep 1.5
    mainmenufunc
elif [[ "$password" == "sysadmin571_bypass/:" ]]; then
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    hacking_game
elif [[ "$password" == "exit" ]]; then
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    echo "Goodbye!" && exit
else
    play -q $BASE_DIR/ui_hacking_passbad.wav -t alsa
    echo "Incorrect password. Please try again." | pv -qL 200
    loginfunc
fi
}



# Function to generate a random string of characters
generate_random_chars() {
    local len=$1
    tr -dc 'A-Za-z0-9!@#$%^&*()_+-=[]{}|;:,.<>/?' < /dev/urandom | head -c $len
}

# Function to insert passwords randomly into a line of random characters
generate_line_with_password() {
    local password=$1
    local line_length=60  # Increased line length to accommodate spacing
    local password_length=${#password}
    local start=$(( RANDOM % (line_length - password_length - 2) + 1 ))  # Ensure space for leading and trailing spaces
    local pre=$(generate_random_chars $start)
    local post=$(generate_random_chars $(( line_length - start - password_length - 2 )))
    echo "$pre $password $post"  # Spaces added around the password
}

# Function to display the hacking interface
display_interface() {
    local start_line=3  # Starting line for passwords display
    tput cup 0 0
    echo "0xF9C1 |$(generate_random_chars 10)|"
    for i in "${!passwords[@]}"; do
        line=$(generate_line_with_password "${passwords[$i]}")
        tput cup $((start_line + i)) 0
        if [[ $i -eq $cursor_position ]]; then
            pre=${line%%${passwords[$i]}*}
            post=${line#*${passwords[$i]}}
            echo -n "|$pre"
            tput setab 4
            echo -n "${passwords[$i]}"
            tput sgr0
            echo "|$post"
        else
            echo "|$line|"
        fi
    done
    tput cup $((start_line + ${#passwords[@]})) 0
    echo "|$(generate_random_chars 50)| 0xFA3E"
}

# Function to update a single line
update_line() {
    local index=$1
    local start_line=3  # Starting line for passwords display
    tput cup $((start_line + index)) 0
    line=$(generate_line_with_password "${passwords[$index]}")
    if [[ $index -eq $cursor_position ]]; then
        pre=${line%%${passwords[$index]}*}
        post=${line#*${passwords[$index]}}
        echo -n "|$pre"
        tput setab 4
        echo -n "${passwords[$index]}"
        tput sgr0
        echo "|$post"
    else
        echo "|$line|"
    fi
}

# Function to center multiline text
left_multiline_text() {
    local lines=("$@")
    for line in "${lines[@]}"; do
        printf "%s\n" "$line"
    done
}

# Function to display attempt count and closeness at the bottom of the screen
display_attempt_info() {
    local attempts=$1
    local max_attempts=$2
    local correct_count=$3
    local term_height=$(tput lines)
    tput cup $((term_height - 1)) 0
    printf "Attempts used: %d/%d | Correct letters: %d/%d" "$attempts" "$max_attempts" "$correct_count" "${#correct_password}"
}

# Function to clear the attempt info area
clear_attempt_info() {
    local term_height=$(tput lines)
    tput cup $((term_height - 1)) 0
    printf "%-50s" ""
}

# Function to start the game
hacking_game() {
    clear
    passwords=("WINTER" "FILTER" "MINTER" "KITTEN" "BINDER" "WINNER" "FINDER" "THINKER" "SPLINTER" "TINKER" "CLINKER" "SINKER" "PINKER" "RISKER" "BLINKER")
    local max_attempts=6
    local cursor_position=0

    # Randomly select one password from the list
    local correct_password="${passwords[$RANDOM % ${#passwords[@]}]}"

    # Initialize attempts
    local attempt_count=0
    local guess=""
    local correct_count=0

    left_multiline_text "Passcode Bypass Terminal Activated"
    left_multiline_text "Guess the password. All passwords have ${#correct_password} characters."
    echo
    read -p "Press enter to continue"
    
    display_interface
    display_attempt_info $attempt_count $max_attempts $correct_count

    while (( attempt_count < max_attempts )); do
        while true; do
            read -s -n 1 key
            case "$key" in
                $'\x1b')  # Escape sequence
                    read -s -n 1 -t 0.1 key
                    if [[ "$key" == "[" ]]; then
                        read -s -n 1 -t 0.1 key
                        case "$key" in
                            "A")  # Up arrow
                                previous_position=$cursor_position
                                ((cursor_position--))
                                if (( cursor_position < 0 )); then
                                    cursor_position=$((${#passwords[@]} - 1))
                                fi
                                update_line $previous_position
                                update_line $cursor_position
                                ;;
                            "B")  # Down arrow
                                previous_position=$cursor_position
                                ((cursor_position++))
                                if (( cursor_position >= ${#passwords[@]} )); then
                                    cursor_position=0
                                fi
                                update_line $previous_position
                                update_line $cursor_position
                                ;;
                        esac
                    fi
                    ;;
                "")  # Enter key
                    guess=${passwords[$cursor_position]}
                    break
                    ;;
            esac
        done

        guess=$(echo "$guess" | tr '[:lower:]' '[:upper:]')  # Convert to uppercase for comparison

        # Check if guess is valid
        if [[ "${#guess}" -ne "${#correct_password}" ]]; then
            clear_attempt_info
            aplay "$BASE_DIR/ui_hacking_passbad.wav" > /dev/null 2>&1
            display_attempt_info $attempt_count $max_attempts $correct_count
            continue
        fi

        # Check if the guess is correct
        if [[ "$guess" == "$correct_password" ]]; then
            clear_attempt_info
            sleep 1.5
            clear
            aplay "$BASE_DIR/ui_hacking_passgood.wav" > /dev/null 2>&1
            welcome_art=$(cat <<-EOF
                Access Granted.
                Welcome, Overseer.
EOF
            )

            left_multiline_text "$welcome_art"
            sleep 1.5
            aplay "$BASE_DIR/ui_hacking_charscroll.wav" > /dev/null 2>&1
            mainmenufunc
            return  # Exit the game loop and function after success
        fi

        # Calculate correct letters in the correct positions
        correct_count=$(check_password "$guess" "$correct_password")
        clear_attempt_info
        aplay "$BASE_DIR/ui_hacking_passbad.wav" > /dev/null 2>&1
        ((attempt_count++))
        display_attempt_info $attempt_count $max_attempts $correct_count
        sleep 1

        # Check for attempt exhaustion
        if (( attempt_count >= max_attempts )); then
            clear_attempt_info
            clear
            aplay "$BASE_DIR/ui_hacking_passbad.wav" > /dev/null 2>&1
            left_multiline_text "Terminal locked. Starting cooldown..."
            for (( i=10; i>0; i-- )); do
                aplay "$BASE_DIR/ui_hacking_charscroll.wav" > /dev/null 2>&1
                left_multiline_text "$i... "
                sleep 1
            done
            aplay "$BASE_DIR/ui_hacking_charenter_01.wav" > /dev/null 2>&1
            left_multiline_text "Cooldown complete. You may try again."
            hacking_game
            return  # Exit the current instance of the game loop and function
        fi
    done
}

# Function to compare guess with the correct password
check_password() {
    local guess=$1
    local correct=$2
    local count=0

    for (( i=0; i<${#guess}; i++ )); do
        if [[ "${guess:$i:1}" == "${correct:$i:1}" ]]; then
            ((count++))
        fi
    done

    echo $count
}



# Function to display the main menu
startupfunc() {

   clear

    # Display the Menu text
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa

    # Display the menu options
    COLUMNS=12
    options=("Login" "Exit" "Terminal")
    selected=0

     # Function to print the menu options with cursor highlighting
    print_menu() {
        for i in "${!options[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "\e[7m${options[$i]}\e[0m"
            else
                echo "${options[$i]}"
            fi
        done
    }

    # Print the initial menu
    print_menu

# Read the user input
    while read -rsn1 key; do
        case $key in
            A) # Up arrow key
                ((selected--))
                if [[ $selected -lt 0 ]]; then
                    selected=$((${#options[@]} - 1))
                fi
                ;;
            B) # Down arrow key
                ((selected++))
                if [[ $selected -ge ${#options[@]} ]]; then
                    selected=0
                fi
                ;;
            "") # Enter key
                case $selected in
                    0)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        clear
                        loginfunc
                        ;;
                    1)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        
                        echo "Goodbye!"
                        exit
                        ;;
                    2)
                        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
                        
                        check_security_key
                        ;;

                esac
                break
                ;;
        esac

        # Clear the screen and print the updated menu
        clear
        display_center "$BASE_DIR/greeterheader.txt"
        echo "$greeter"
        print_menu
    done
}


# Define the spinner characters
spinner="/-\|"

# Define the number of iterations
iterations=50


# Function to display the spinner and progress bar centered in the terminal
spin() {
    local i=0
    local terminal_width=$(tput cols)
    local terminal_height=$(tput lines)
    local padding_horizontal=$(( (terminal_width - 24) / 2 )) # Calculate horizontal padding for centering
    local padding_vertical=$(( (terminal_height / 2) - 1 )) # Calculate vertical padding for centering

    # Print empty lines for vertical centering
    for (( j = 0; j < padding_vertical; j++ )); do
        printf "\n"
    done

    printf "%*s%s\n" $padding_horizontal "" "Launching Interface"


    while [ $i -lt $iterations ]; do
        # Calculate progress
        progress=$((i * 100 / iterations))
        # Calculate the length of the progress bar based on progress
        bar_length=$((i * 20 / iterations))
        # Generate the progress bar string
        progress_bar=$(printf '=%.0s' $(seq 1 $bar_length))
        # Display spinner and progress bar centered
        printf "\r%*s[%c] [%-${bar_length}s] %d%%" $padding_horizontal "" "${spinner:i++%${#spinner}:1}" "$progress_bar" "$progress"
        sleep 0.1
    done
}

#some random aesthetic startup junk
clear
play -q $BASE_DIR/computerstart.wav -t alsa &
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Initiating Etherflow Circuits... | pv -qL 80
sleep 3
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Loading Unified OS...  | pv -qL 80
sleep 0.5
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Calibrating Mana Cores to Ley Lines...  | pv -qL 80
sleep 0.2
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Syncing with Astral Chronometers...  | pv -qL 80
sleep 0.8
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Securing with Ward Locks and Glyphs...  | pv -qL 80
sleep 0.4
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Engaging Arcane Logic Engines...  | pv -qL 80
sleep 0.9
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo Compiling Spell Scripts...  | pv -qL 80
sleep 0.3
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
clear
spin
sleep 1
clear

# ASCII Art as a single string, preserving new lines
ascii_art=$(cat <<-EOF
████████╗ █████╗ ██╗██████╗ 
╚══██╔══╝██╔══██╗██║██╔══██╗
   ██║   ███████║██║██████╔╝
   ██║   ██╔══██║██║██╔══██╗
   ██║   ██║  ██║██║██████╔╝
   ╚═╝   ╚═╝  ╚═╝╚═╝╚═════╝
EOF
)

center_multiline_text "$ascii_art"

#echo "==============================================" | pv -qL 50
play -q $BASE_DIR/ui_hacking_passgood.wav -t alsa
sleep 3


#goes to the main men
# Call the login function
startupfunc

